app:
  config:
    unprotected-endpoints: 
      post: >
        /api/users/register

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: ${DB_HOST:jdbc:postgresql://localhost:5432/interview}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
